## Part 1

Import the libraries

In [3]:
import pandas as pd

Load the CSV dataset using Pandas

In [4]:
##read_csv("data.csv")
df = pd.read_excel("C:/Users/My/Desktop/Data_Analytics/Python/Project/sales_data_2000_rows (2).xlsx")

Display first 5 rows

In [6]:
df.head()

   Order_ID        Date  Product     Category       City  Quantity  Price
0      1001  2025-02-19  Printer  Electronics    Kolkata       3.0   9591
1      1002  2025-08-08     Pens   Stationery  Hyderabad       5.0    318
2      1003  2025-07-28    Mouse  Electronics    Chennai       1.0    697
3      1004  2025-08-15    Chair    Furniture  Ahmedabad       1.0   3410
4      1005  2025-04-12    Mouse  Electronics     Mumbai       NaN    624

Check Dataset Information

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  2000 non-null   int64
 1   Date      2000 non-null   str
 2   Product   2000 non-null   str
 3   Category  2000 non-null   str
 4   City      2000 non-null   str
 5   Quantity  1999 non-null   float64
 6   Price     2000 non-null   int64
dtypes: float64(1), int64(2), str(4)
memory usage: 109.5 KB

##Expected Libraries
*pandas
*matplotlib

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

Part 2 — Data Cleaning
Tasks

In [ ]:
##Check missing values

print("Missing values:")
print(df.isnull().sum())

Missing values:
Order_ID    0
Date        0
Product     0
Category    0
City        0
Quantity    1
Price       0
dtype: int64

In [12]:
##Remove duplicate records

## Check duplicate records
print("Duplicate records:", df.duplicated().sum())

## Remove duplicates
df = df.drop_duplicates()

Duplicate records: 0

In [5]:
##Correct spelling mistakes if any

df['Product'] = df['Product'].replace({
    'Pen': 'Pens'
})

In [10]:
##Convert Date column into datetime format
df['Date'] = pd.to_datetime(df['Date'])
df.dtypes

Order_ID             int64
Date        datetime64[us]
Product                str
Category               str
City                   str
Quantity           float64
Price                int64
dtype: object

In [11]:
##Expected Output - Clean and structured dataset.

df.head()

   Order_ID       Date  Product     Category       City  Quantity  Price
0      1001 2025-02-19  Printer  Electronics    Kolkata       3.0   9591
1      1002 2025-08-08     Pens   Stationery  Hyderabad       5.0    318
2      1003 2025-07-28    Mouse  Electronics    Chennai       1.0    697
3      1004 2025-08-15    Chair    Furniture  Ahmedabad       1.0   3410
4      1005 2025-04-12    Mouse  Electronics     Mumbai       NaN    624

Part 3 — Data Processing
Tasks

Create a new column:

Revenue = Quantity × Price

Add the Revenue column to the dataset.